/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Homework1;

import java.util.Arrays;

public class App {

    public static void main(String[] args) {
        
    }

    public static int[] createArrayWithLimits(int[] arr,int maxLength,int minElement,int maxElement){
        
        //check input array
        if( arr==null ){
            return null;
        }
        if( arr.length == 0){
            return null;
        }

        //sorting input array
        Arrays.sort(arr);

        //create array
        int[] newArr = new int[maxLength]; 

        int i=0;
        //min kontrol
        if(arr[arr.length-1]<minElement){
            return null;
        }
        //max kontrol
        if(arr[0]>maxElement){
            return null;
        }
        //starting point
        while(arr[i]<minElement){
            i++;
        }      

        int j=0;
        for(;i<arr.length;i++){
            //ending point
            if(arr[i]>maxElement || j>(maxLength-1)){
                break;
            }
            newArr[j]=arr[i];
            j++;
        }
        return newArr;
    }
}
