/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Homework1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void testNullArray() {
        int[] arr = null;
        assertNull(App.createArrayWithLimits(arr,1,1,1));
    }
    @Test void testEmptyArray() {
        int[] arr = new int[0];
        assertNull(App.createArrayWithLimits(arr,1,1,1));
    }
    @Test void testMin(){
        int[] arr = new int[3];
        arr[0]=1;
        arr[1]=2;
        arr[2]=3;
        assertNull(App.createArrayWithLimits(arr,1,5,1));
    }
    @Test void testMax(){
        int[] arr = new int[3];
        arr[0]=3;
        arr[1]=6;
        arr[2]=4;
        assertNull(App.createArrayWithLimits(arr,1,1,2));
    }
    @Test void testCorrectArray(){
        int[] arr = new int[7];
        arr[0]=3;
        arr[1]=6;
        arr[2]=4;
        arr[3]=5;
        arr[4]=0;
        arr[5]=-1;
        arr[6]=23;

        int[] expected = new int[4];
        expected[0]=3;
        expected[1]=4;
        expected[2]=5;
        expected[3]=6;
        assertArrayEquals(expected, App.createArrayWithLimits(arr,4,2,12));
        
    }
}
